### ISSUE TITLE
Error in demo

### ISSUE THREAD

**Issue by conradludgate** [fatihtelis/react-lorem-ipsum#1]
In the demo, in the random user page, you provide the code block

```js
<div className="user">
  <Avatar gender="female">
  <div className="fullname">{fullname('female')}</div>
  <div className="username">{`@${username()`}</div>
</div>
```

Which has a bug in the username line, the inline string formatting will not compile, it should be 
```diff
-   <div className="username">{`@${username()`}</div>
+   <div className="username">{`@${username()}`}</div>
```

**Comment by fatihtelis** [comment]
Hi Conrad. I've merged your pull request. A typical typo error. :) Thanks for your contribution.
