### ISSUE TITLE
Add flag for freezing the contents of the Lorem ipsum

### ISSUE THREAD

**Issue by PupoSDC** [fatihtelis/react-lorem-ipsum#13]
It would be mega convenient to have a flag that basically freezes the contents of the `LoremIpsum` after the first render. This would be very useful when using this component inside dynamic views so that when the parent re-renders the generated text remains constant and does not affect the placeholder experience. for example, in my story book, i have:

```jsx
<Preview>
  <Story
    name="Example Report desktop"
    inline={false}
    height={500}
    args={{ title: 'Personality Test', onCancelClick: null, activePage: "1" }}>
    {(args) => {
      const [activePage, setActivePage] = useState(args.activePage);
      useEffect(() => setActivePage(args.activePage), [args.activePage]);
      return (
        <div>
          <ReportContainer {...args} setActivePage={setActivePage} activePage={activePage}>
            <ReportPage id="1" title="Your Personality">
              <LoremIpsum p={3} />
              <input value={activePage} onChange={(e) => setActivePage(e.target.value)}/>
            </ReportPage>
        </div>
      );
    }}
  </Story>
</Preview>
```

so every time i press that input, the whole page changes completely.

**Comment by fatihtelis** [comment]
Hi @PupoSDC, I've merged #14 which adds this nice feature. Thanks for your effort. 👍🏻 It's available at react-lorem-ipsum@1.4.8 and future versions.

**Comment by PupoSDC** [comment]
during my migration i noticed that `loremIpsum({ p: 3, random: false })` returns `['', '', '']`. `No regression for `random: true` :(

**Comment by fatihtelis** [comment]
@PupoSDC Thanks for reporting. I made a quick fix for the issue and publish react-lorem-ipsum@1.4.9 by setting default props for the createStandardParagraph function. I will write tests for "loremIpsum" function too as soon as I have time.

**Comment by PupoSDC** [comment]
again, awesome, thanks!
